name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch libs
      run: sudo apt-get install libcurl4-openssl-dev && sudo apt-get install libssl-dev
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
